"""
This type stub file was generated by pyright.
"""

from numba.core.datamodel.registry import register_default
from numba.core.extending import models, register_model
from numba.core import types
from numba.cuda.types import Dim3, GridGroup

@register_model(Dim3)
class Dim3Model(models.StructModel):
    def __init__(self, dmm, fe_type) -> None:
        ...
    


@register_model(GridGroup)
class GridGroupModel(models.PrimitiveModel):
    def __init__(self, dmm, fe_type) -> None:
        ...
    


@register_default(types.Float)
class FloatModel(models.PrimitiveModel):
    def __init__(self, dmm, fe_type) -> None:
        ...
    


