"""
하이킨아시 도지 전략 비교
======================================================================
다음 1봉만 vs 다음 3봉 확인 비교
"""

import pandas as pd

print("=" * 80)
print("하이킨아시 도지 전략 성과 비교")
print("=" * 80)
print()

# 1봉 전략 결과
print("【전략 A: 다음 1봉만 확인】")
print("  파일: heikin_ashi_doji_simple.py")
print()
print("  필터 1: 필터 없음")
print("    거래: 7798개 (연 1560개)")
print("    승률: 44.49%")
print("    평균: -0.188%")
print("    5년: -1469%")
print()
print("  필터 2: 다음봉 +0.5%+ 상승 ⭐")
print("    거래: 31개 (연 6개)")
print("    승률: 51.6%")
print("    평균: -0.024%")
print("    5년: -0.74%")
print("    상태: NEARLY BREAK-EVEN!")
print()
print("  필터 3: 다음봉 +1.0%+ 상승")
print("    거래: 2개")
print("    승률: 50%")
print()

print("-" * 80)
print()

# 3봉 전략 결과
print("【전략 B: 다음 3봉 확인】")
print("  파일: heikin_ashi_doji_3bars_v2.py")
print()
print("  필터 1: 3개 모두 상승")
print("    거래: 7798개 (연 1560개)")
print("    승률: 44.49%")
print("    평균: -0.188%")
print("    5년: -1469%")
print()
print("  필터 2: 3개 상승 + 평균 0.5%+ ⭐")
print("    거래: 502개 (연 100개)")
print("    승률: 47.41%")
print("    평균: -0.125%")
print("    5년: -62.67%")
print("    상태: 여전히 손실")
print()
print("  필터 3: 3개 상승 + 순차 증가")
print("    거래: 4868개 (연 974개)")
print("    승률: 43.82%")
print("    평균: -0.201%")
print("    5년: -979%")
print()

print("=" * 80)
print("핵심 발견")
print("=" * 80)
print()

print("✅ 1봉 확인 (다음봉 +0.5%+):")
print("   • 승률: 51.6%")
print("   • 거래: 31개 (5년)")
print("   • 손실: -0.74%")
print("   • 진입: 도지 후 2번째 봉 (빠름)")
print()

print("❌ 3봉 확인 (3개 상승 + 0.5%+):")
print("   • 승률: 47.41%")
print("   • 거래: 502개 (5년)")
print("   • 손실: -62.67%")
print("   • 진입: 도지 후 4번째 봉 (늦음)")
print()

print("📊 왜 3봉이 더 나쁜가?")
print("   1. 진입 지연: 4번째 봉에 진입 → 이미 움직임 끝")
print("   2. 더 많은 거짓 신호: 502개 vs 31개")
print("   3. 확인 과잉: 3봉 기다리는 동안 모멘텀 소실")
print("   4. 승률 악화: 51.6% → 47.41%")
print()

print("🎯 결론:")
print("   더 많은 확인 ≠ 더 좋은 성과")
print("   빠른 진입 + 강한 필터 > 느린 진입 + 많은 확인")
print()

print("💡 다음 시도:")
print("   1. 1봉 전략 최적화 (TP/SL 조정)")
print("   2. 도지 정의 변경 (body < 5%?)")
print("   3. 추가 필터 (거래량, ATR 등)")
print("   4. 다른 접근법 시도")
print()
print("=" * 80)
