from typing import Any, Optional, Union
import pandas as pd
import numpy as np

# 메인 함수들
def add_all_ta_features(
    df: pd.DataFrame,
    open: str = "Open",
    high: str = "High",
    low: str = "Low", 
    close: str = "Close",
    volume: str = "Volume",
    fillna: bool = False,
    colprefix: str = ""
) -> pd.DataFrame: ...

# 카테고리별 함수들
def add_trend_ta(df: pd.DataFrame, **kwargs: Any) -> pd.DataFrame: ...
def add_volume_ta(df: pd.DataFrame, **kwargs: Any) -> pd.DataFrame: ...
def add_volatility_ta(df: pd.DataFrame, **kwargs: Any) -> pd.DataFrame: ...
def add_momentum_ta(df: pd.DataFrame, **kwargs: Any) -> pd.DataFrame: ...
def add_others_ta(df: pd.DataFrame, **kwargs: Any) -> pd.DataFrame: ...

# 개별 지표들 (자주 사용하는 것들)
def sma(close: pd.Series, window: int = 14, fillna: bool = False) -> pd.Series: ...
def ema(close: pd.Series, window: int = 14, fillna: bool = False) -> pd.Series: ...
def rsi(close: pd.Series, window: int = 14, fillna: bool = False) -> pd.Series: ...
def macd(close: pd.Series, window_slow: int = 26, window_fast: int = 12, window_sign: int = 9, fillna: bool = False) -> pd.DataFrame: ... 