"""
This type stub file was generated by pyright.
"""

import os
import logging
import subprocess
import tempfile
import sys
from .cc import CC
from .decorators import export, exportmany

def get_ending(args): # -> Literal['.bc', '.o']:
    ...

def main(args=...): # -> None:
    ...

