"""
This type stub file was generated by pyright.
"""

class DataModelManager:
    """Manages mapping of FE types to their corresponding data model
    """
    def __init__(self) -> None:
        ...
    
    def register(self, fetypecls, handler): # -> None:
        """Register the datamodel factory corresponding to a frontend-type class
        """
        ...
    
    def lookup(self, fetype):
        """Returns the corresponding datamodel given the frontend-type instance
        """
        ...
    
    def __getitem__(self, fetype):
        """Shorthand for lookup()
        """
        ...
    
    def copy(self): # -> DataModelManager:
        """
        Make a copy of the manager.
        Use this to inherit from the default data model and specialize it
        for custom target.
        """
        ...
    


