"""
This type stub file was generated by pyright.
"""

from numba.core import types
from numba.core.extending import overload_method

"""
Implementation of method overloads for Generator objects.
"""
@overload_method(types.NumPyRandomGeneratorType, 'random')
def NumPyRandomGeneratorType_random(inst, size=..., dtype=...): # -> Callable[..., Any | Signature]:
    ...

