"""
This type stub file was generated by pyright.
"""

import os

'''Helper to preload vcomp140.dll and msvcp140.dll to prevent
"not found" errors.

Once vcomp140.dll and msvcp140.dll are
preloaded, the namespace is made available to any subsequent
vcomp140.dll and msvcp140.dll. This is
created as part of the scripts that build the wheel.
'''
if os.name == "nt":
    libs_path = ...
    vcomp140_dll_filename = ...
    msvcp140_dll_filename = ...
