"""
This type stub file was generated by pyright.
"""

import numpy as np
from numba.core.extending import overload

"""
Implementation of operations involving polynomials.
"""
@overload(np.roots)
def roots_impl(p): # -> Callable[..., NDArray[bool_ | object_ | void | floating[_64Bit]] | Any]:
    ...

