# 모델 설정
model:
  input_dim: 40  # 입력 피처 차원
  model_dim: 256  # 모델 차원
  num_heads: 8  # 어텐션 헤드 수
  num_layers: 6  # 트랜스포머 레이어 수
  num_timeframes: 6  # 사용할 시간대 수 (5m, 15m, 1h, 4h, 1d, 1w)
  dropout: 0.1  # 드롭아웃 비율
  use_pe: true  # 포지셔널 인코딩 사용 여부

# 데이터 설정
data:
  data_dir: "data/processed"  # 데이터 디렉토리
  features: ["sma_20", "sma_50", "rsi", "bb_upper", "bb_middle", "bb_lower", "macd", "macd_signal", "vwap", "atr", "returns"]  # 사용할 피처
  timeframes: ["5m", "15m", "60m", "240m", "1d"]  # 사용할 시간대
  train_ratio: 0.7  # 학습 데이터 비율
  val_ratio: 0.15  # 검증 데이터 비율
  test_ratio: 0.15  # 테스트 데이터 비율
  batch_size: 64  # 배치 크기
  seq_len: 100  # 시퀀스 길이
  num_workers: 4  # 데이터 로더 워커 수

# 학습 설정
training:
  num_epochs: 100  # 최대 에포크 수
  learning_rate: 1e-4  # 학습률
  weight_decay: 1e-5  # 가중치 감쇠
  clip_grad_norm: 1.0  # 그래디언트 클리핑
  patience: 10  # 얼리스토핑 인내심
  min_delta: 1e-4  # 개선으로 간주할 최소 변화량
  use_amp: true  # 자동 혼합 정밀도 사용 여부
  checkpoint_dir: "models/checkpoints"  # 체크포인트 저장 디렉토리
  log_dir: "logs"  # 로그 저장 디렉토리

# 손실 함수 가중치
loss_weights:
  direction: 1.0  # 방향성 분류 가중치
  magnitude: 0.5  # 크기 회귀 가중치
  duration: 0.3  # 지속 기간 회귀 가중치
  confidence: 0.2  # 신뢰도 가중치
  risk: 0.5  # 리스크 패널티 가중치

# 시장 레짐 감지기 설정
regime_detector:
  lookback_period: 20  # 레짐 감지에 사용할 기간
  adx_threshold: 25  # 추세 강도 임계값
  rsi_threshold: 30  # RSI 과매수/과매도 임계값
  atr_multiplier: 2.0  # 변동성 임계값 승수

# 온라인 적응 설정
online_adaptation:
  adaptation_interval: 3600  # 초 단위 (1시간)
  max_adaptation_steps: 100  # 최대 적응 스텝 수
  inference_interval: 60  # 초 단위 (1분)
  enable_adaptation: true  # 모델 적응 활성화 여부
  enable_inference: true  # 추론 활성화 여부

# 로깅 설정
logging:
  level: "INFO"  # 로그 레벨 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "logs/training.log"  # 로그 파일 경로
  console: true  # 콘솔 출력 여부
