"""
This type stub file was generated by pyright.
"""

import enum
import numpy as np
from functools import singledispatch
from numba.np.numpy_support import numpy_version
from numpy.random._bit_generator import BitGenerator
from numpy.random.bit_generator import BitGenerator

_termcolor = ...
if numpy_version < (1, 19):
    ...
else:
    ...
class Purpose(enum.Enum):
    argument = ...
    constant = ...


_TypeofContext = ...
def typeof(val, purpose=...): # -> ByteArray | PyArray | Buffer | ExternalFunctionPointer | Opaque | Any:
    """
    Get the Numba type of a Python value for the given purpose.
    """
    ...

@singledispatch
def typeof_impl(val, c): # -> ByteArray | PyArray | Buffer | ExternalFunctionPointer | Opaque | Any | None:
    """
    Generic typeof() implementation.
    """
    ...

@typeof_impl.register(BitGenerator)
def typeof_numpy_random_bitgen(val, c): # -> NumPyRandomBitGeneratorType:
    ...

@typeof_impl.register(np.random.Generator)
def typeof_random_generator(val, c): # -> NumPyRandomGeneratorType:
    ...

