"""
This type stub file was generated by pyright.
"""

from numba.core.imputils import lower_builtin

"""
This file implements the lowering for `dict()`
"""
@lower_builtin(dict)
def impl_dict(context, builder, sig, args):
    """
    The `dict()` implementation simply forwards the work to `Dict.empty()`.
    """
    ...

