"""
This type stub file was generated by pyright.
"""

from collections.abc import MutableMapping
from numba.core.types import DictType
from numba.core.imputils import numba_typeref_ctor
from numba.core import types
from numba.core.extending import box, overload, overload_classmethod, type_callable, unbox

"""
Python wrapper that connects CPython interpreter to the numba dictobject.
"""
class Dict(MutableMapping):
    """A typed-dictionary usable in Numba compiled functions.

    Implements the MutableMapping interface.
    """
    def __new__(cls, dcttype=..., meminfo=...): # -> dict[Any, Any] | Self:
        ...
    
    @classmethod
    def empty(cls, key_type, value_type): # -> dict[Any, Any] | Self:
        """Create a new empty Dict with *key_type* and *value_type*
        as the types for the keys and values of the dictionary respectively.
        """
        ...
    
    def __init__(self, **kwargs) -> None:
        """
        For users, the constructor does not take any parameters.
        The keyword arguments are for internal use only.

        Parameters
        ----------
        dcttype : numba.core.types.DictType; keyword-only
            Used internally for the dictionary type.
        meminfo : MemInfo; keyword-only
            Used internally to pass the MemInfo object when boxing.
        """
        ...
    
    def __getitem__(self, key):
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def __delitem__(self, key): # -> None:
        ...
    
    def __iter__(self): # -> Iterator[Never] | Iterator[Any]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __contains__(self, key): # -> bool:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def get(self, key, default=...): # -> None:
        ...
    
    def setdefault(self, key, default=...):
        ...
    
    def popitem(self):
        ...
    
    def copy(self):
        ...
    


@overload_classmethod(types.DictType, 'empty')
def typeddict_empty(cls, key_type, value_type): # -> Callable[..., dict[Any, Any]] | None:
    ...

@box(types.DictType)
def box_dicttype(typ, val, c):
    ...

@unbox(types.DictType)
def unbox_dicttype(typ, val, c): # -> NativeValue:
    ...

@type_callable(DictType)
def typeddict_call(context): # -> Callable[[], DictType]:
    """
    Defines typing logic for ``Dict()``.
    Produces Dict[undefined, undefined]
    """
    ...

@overload(numba_typeref_ctor)
def impl_numba_typeref_ctor(cls): # -> Callable[..., dict[Any, Any] | Dict] | None:
    """
    Defines ``Dict()``, the type-inferred version of the dictionary ctor.

    Parameters
    ----------
    cls : TypeRef
        Expecting a TypeRef of a precise DictType.

    See also: `redirect_type_ctor` in numba/cpython/bulitins.py
    """
    ...

